# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution_profile',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='subscriber_profile',
            name='sub_name',
        ),
        migrations.DeleteModel(
            name='Subscriber_profile',
        ),
    ]
