# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teapp', '0002_auto_20170701_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('regd_last_date', models.DateField()),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teapp.Categories')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teapp.Cities')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teapp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event_details',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teapp.States'),
        ),
        migrations.AddField(
            model_name='event_details',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teapp.Streams'),
        ),
    ]
