# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teapp', '0003_auto_20170701_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=12)),
                ('institution_name', models.CharField(max_length=50)),
                ('institution_website', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cont_person_name',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
