# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teapp', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regd_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teapp.Event_Details')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='teapp.Subscriber')),
            ],
        ),
    ]
